[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5001"
FLASK_ENV = "production"
HOST = "0.0.0.0"
CACHE_DURATION_HOURS = "24"
LOG_LEVEL = "INFO"
